import numpy as np


description_replace_mapping = {
    "Ball": "ball",
    "In play, run(s)": "hit_into_play",
    "In play, out(s)": "hit_into_play",
    "In play, no out": "hit_into_play",
    "Called Strike": "called_strike",
    "Foul": "foul",
    "Swinging Strike": "swinging_strike",
    "Blocked Ball": "ball",
    "Swinging Strike (Blocked)": "swinging_strike",
    "Foul Tip": "swinging_strike",
    "Foul Bunt": "foul",
    "Hit By Pitch": "hit_by_pitch",
    "Pitchout": "ball",
    "Missed Bunt": "swinging_strike",
    "Bunt Foul Tip": "swinging_strike",
    "Foul Pitchout": "foul",
    "Ball In Dirt": "ball",
}

event_replace_mapping = {
    'game_advisory': None,
    'single': 'single',
    'walk': 'walk',
    # np.nan: None,
    'strikeout': 'strikeout',
    'field_out': 'field_out',
    'force_out': 'field_out',
    'double': 'double',
    'hit_by_pitch': 'hit_by_pitch',
    'home_run': 'home_run',
    'grounded_into_double_play': 'field_out',
    'fielders_choice_out': 'field_out',
    'fielders_choice': 'field_out',
    'field_error': None,
    'double_play': 'field_out',
    'sac_fly': 'field_out',
    'strikeout_double_play': None,
    'triple': 'triple',
    'caught_stealing_2b': None,
    'sac_bunt': 'field_out',
    'catcher_interf': None,
    'caught_stealing_3b': None,
    'sac_fly_double_play': 'field_out',
    'triple_play': 'field_out',
    'other_out': 'field_out',
    'pickoff_3b': None,
    'caught_stealing_home': None,
    'pickoff_1b': None,
    'pickoff_2b': None,
    'wild_pitch': None,
    'stolen_base_2b': None,
    'pickoff_caught_stealing_3b': None,
    'pickoff_caught_stealing_2b': None,
    'sac_bunt_double_play': None,
    'passed_ball': None,
    'pickoff_caught_stealing_home': None
}